name: dca_digital_digests
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  shared_preferences: ^2.0.8
  provider: ^6.0.4
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  path_provider: ^2.0.11
  bloc: ^8.1.0
  mailer: ^6.0.0
  cached_network_image: ^3.2.2
  http: ^0.13.3
  flutter_web_browser: ^0.15.0
  scrollable_positioned_list: ^0.1.7
  html: ^0.15.0
  url_launcher: ^6.0.3
  dio: ^4.0.6
  intl: ^0.17.0
  percent_indicator: ^3.0.1
  timelines: ^0.1.0
  dots_indicator: ^2.0.0
  flutter_credit_card: ^2.0.0
  intl_phone_field: ^2.0.0
  email_validator: ^2.0.1
  mobx: ^2.0.1
  numeric_keyboard: ^1.1.0
  bottom_navigation_badge: ^1.0.3
  clippy_flutter: ^1.1.1
  flutter_staggered_grid_view: ^0.4.0
  video_player: ^2.1.10
  algolia: ^1.0.1
  image_picker: ^0.8.2
  file_picker: ^3.0.3
  fl_chart: ^0.36.3
  persistent_bottom_nav_bar: any
  chewie: ^1.2.2
  local_auth: ^1.1.6
  expandable: ^5.0.1
  device_info: ^2.0.2
  encrypt: ^5.0.1
  avatar_letter: ^1.0.1
  charts_flutter:
      git:
        url: https://github.com/google/charts.git
        path: charts_flutter
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  flutter_local_notifications: ^9.0.1
  flutter_tawk: ^0.0.5
  get: ^4.6.5
  store_redirect: ^2.0.1
  rating_dialog: ^2.0.4
  flutter_inappwebview: ^5.7.1
  flutter_native_splash: ^2.2.0+1
  animated_text_kit: ^4.2.2
  firebase_database: ^10.0.14
  share: ^2.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
